tap "bramstein/webfonttools"
tap "carlocab/personal"
tap "cloudflare/cloudflare"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "khanhas/tap"
tap "mongodb/brew"
brew "ack"
brew "act"
brew "python@3.10"
brew "ansible"
brew "giflib"
brew "jpeg"
brew "autoconf"
brew "automake"
brew "python@3.9"
brew "glib"
brew "pkg-config"
brew "cairo"
brew "chezmoi"
brew "coreutils"
brew "libtool"
brew "libevent"
brew "p11-kit"
brew "unbound"
brew "gnutls"
brew "gobject-introspection"
brew "harfbuzz"
brew "ffmpeg"
brew "findutils"
brew "ghostscript"
brew "git"
brew "git-lfs"
brew "gnupg"
brew "go"
brew "grep"
brew "jq"
brew "ldns"
brew "libfido2"
brew "pango"
brew "librsvg"
brew "llvm"
brew "lynx"
brew "mas"
brew "moreutils"
brew "ncurses"
brew "neofetch"
brew "nghttp2"
brew "node@16"
brew "openjdk"
brew "openssh"
brew "p7zip"
brew "pigz"
brew "pinentry-mac"
brew "pv"
brew "rename"
brew "rlwrap"
brew "ssh-copy-id"
brew "starship"
brew "telnet"
brew "terraform"
brew "tmux"
brew "tree"
brew "vbindiff"
brew "wget"
brew "woff2"
brew "youtube-dl"
brew "zopfli"
brew "bramstein/webfonttools/sfnt2woff"
brew "bramstein/webfonttools/sfnt2woff-zopfli"
brew "carlocab/personal/unrar"
brew "cloudflare/cloudflare/cloudflared"
brew "khanhas/tap/spicetify-cli"
brew "mongodb/brew/mongodb-community"
cask "background-music"
cask "discord-canary"
cask "flameshot"
cask "gimp"
mas "AdGuard for Safari", id: 1440147259
mas "Apple Configurator 2", id: 1037126344
mas "Dark Reader for Safari", id: 1438243180
mas "Dashlane", id: 517914548
mas "Grammarly for Safari", id: 1462114288
mas "Honey", id: 1472777122
mas "MeddleMonkey", id: 1539631953
mas "Octotree", id: 1457450145
mas "Pages", id: 409201541
mas "Parcel", id: 639968404
mas "Pasta", id: 1438389787
mas "Telegram", id: 747648890
mas "Unsplash Wallpapers", id: 1284863847
mas "WhatsApp", id: 1147396723
mas "WireGuard", id: 1451685025
