tap "carlocab/personal"
tap "cloudflare/cloudflare"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "khanhas/tap"
tap "mongodb/brew"
brew "ack"
brew "giflib"
brew "jpeg"
brew "autoconf"
brew "automake"
brew "python@3.9"
brew "glib"
brew "pkg-config"
brew "cairo"
brew "chezmoi"
brew "coreutils"
brew "libtool"
brew "libevent"
brew "unbound", restart_service: true
brew "gnutls"
brew "gobject-introspection"
brew "harfbuzz"
brew "ffmpeg"
brew "findutils"
brew "ghostscript"
brew "git"
brew "git-lfs"
brew "gnupg"
brew "go"
brew "grep"
brew "ldns"
brew "pango"
brew "librsvg"
brew "llvm"
brew "lynx"
brew "mas"
brew "moreutils"
brew "ncurses"
brew "neofetch"
brew "nghttp2"
brew "node@16"
brew "openjdk"
brew "openssh"
brew "p7zip"
brew "pigz"
brew "pinentry-mac"
brew "pv"
brew "rename"
brew "rlwrap"
brew "ssh-copy-id"
brew "starship"
brew "telnet"
brew "tmux"
brew "tree"
brew "vbindiff"
brew "wget"
brew "woff2"
brew "youtube-dl"
brew "cloudflare/cloudflare/cloudflared"
brew "mongodb/brew/mongodb-community"
mas "Dashlane", id: 517914548
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Slack", id: 803453959
mas "Telegram", id: 747648890
mas "Unsplash Wallpapers", id: 1284863847
mas "WhatsApp", id: 1147396723
mas "WireGuard", id: 1451685025
